[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^7.4
  adafruit/Adafruit PWM Servo Driver Library @ ^3.0
build_flags = -D MQTT_MAX_PACKET_SIZE=2048
